spring:
  application:
    name: API-GATEWAY
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: COLLECT-SERVICE
          uri: lb://COLLECT-SERVICE
          predicates:
            - Path=/collect/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/product_service
        registration:
          spring-gateway:
            authorization-grant-type: authorization_code
            client-id: spring-gateway
            client-secret: 15df18be-9218-429c-9821-60961e3a305a
            provider: keycloak
            redirect-uri: http://localhost:8080/login/oauth2/code/spring-gateway
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/product_service/protocol/openid-connect/certs

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true


