spring:
  application:
    name: API-GATEWAY
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/defaultfallback
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: COLLECT-SERVICE
          uri: lb://COLLECT-SERVICE
          predicates:
            - Path=/collect/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/product_service
        registration:
          vue-front:
#            authorization-grant-type: authorization_code
            client-id: vue-front
#            client-secret: e759a3e9-d81e-4145-bd98-5d74776b1f78
            provider: keycloak
            redirect-uri: http://localhost:8080/login/oauth2/code/vue-front
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/product_service/protocol/openid-connect/certs

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

hystrix:
  command:
    fallbackcmd:
      metrics:
        rollingStates:
          timeInMilliseconds: 1000
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3000
        timeout:
          enabled: true
